# Generated by Django 6.0.3 on 2026-03-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('Pro', 'Tier 3 - Pro Badge'), ('Elite', 'Tier 2 - Elite Badge'), ('Prime', 'Tier 1 - Prime Badge')], max_length=20)),
                ('event_name', models.CharField(help_text='e.g., Inspiro, Illume, Rubix', max_length=100)),
                ('award_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='members.ieeemember')),
            ],
        ),
    ]
